### ISSUE TITLE
[BUG] Scheduler giving wrong output for this testcase

### ISSUE THREAD

**Issue by Tushar-4781** [tijlleenders/ZinZen-scheduler#215] opened 2023-01-03 04:13 UTC
input 

{"startDate":"2023-01-03T00:00:00","endDate":"2023-01-10T00:00:00","goals":[{"id":"e100fe8e-0c19-4a6f-b638-ef82107ea13b","title":"Sleep","duration":"8","after_time":22,"before_time":8},{"id":"db01411c-6b57-4191-8c8b-733ac3751da3","title":"hurdle","duration":"2","start":"2023-01-03T01:00:00","before_time":3},{"id":"b898414d-76d5-4955-891d-b7c4ed7aac62","title":"Lunch","duration":"1","after_time":12,"before_time":14},{"id":"b669fc8f-a431-43e2-952d-285778b1d8ba","title":"Me time","duration":"1"},{"id":"b5fa56c5-3619-41e4-a78f-b468cea90681","title":"Breakfast","duration":"1","after_time":6,"before_time":9},{"id":"7f69d43e-727d-40b7-be8a-47ab2e619c19","title":"Walk","duration":"1","after_time":14,"before_time":20},{"id":"6ff579f6-c1f7-4239-8179-db706856042f","title":"Dinner","duration":"1","after_time":18,"before_time":21},{"id":"2f8d406e-0df2-43ac-a7aa-6e65ff1c5c95","title":"Water the plants indoors","duration":"1","start":"2023-01-03T00:00:00","after_time":1,"before_time":3}]}

output :
![image](https://user-images.githubusercontent.com/39093015/210299173-1b4b8bc4-7ce7-482f-a629-dbda27c63466.png)

the hurdle goal should be the impossible task.
A hurdle goal cannot be divided. 
Next day should not be taken in the account

**Comment by tijlleenders** [comment] 2023-01-03 04:45
Whether someting can be divided should be determined by the user in the frontend, either:
- 'cannot be divided' by default, with special user-defined tag if it can
- 'can be divided' by default, with special user-defined tag if in can't

Since this specification is not in the MVP - I propose we let this slide for now (park in separate issue) and go with the current default ('can be divided').

Ignoring that - there is still a bug in combining start(at_or_after_datettime) with a before(time).

**Comment by egithinji** [comment] 2023-01-03 07:42
Please note that none of the input goals have a repetition. This means that they will be scheduled once somewhere between the calendar start and end, or between their start and deadline (if provided).

So for example the "Sleep" goal is saying 'sleep for 8 hrs, between 22 and 8, somewhere between 3rd Jan and 10th Jan'.

The input is this:
``` 
{
    "startDate": "2023-01-03T00:00:00",
    "endDate": "2023-01-10T00:00:00",
    "goals": [
        {
            "id": "e100fe8e-0c19-4a6f-b638-ef82107ea13b",
            "title": "Sleep",
            "duration": "8",
            "after_time": 22,
            "before_time": 8
        },
        {
            "id": "db01411c-6b57-4191-8c8b-733ac3751da3",
            "title": "hurdle",
            "duration": "2",
            "start": "2023-01-03T01:00:00",
            "before_time": 3
        },
        {
            "id": "b898414d-76d5-4955-891d-b7c4ed7aac62",
            "title": "Lunch",
            "duration": "1",
            "after_time": 12,
            "before_time": 14
        },
        {
            "id": "b669fc8f-a431-43e2-952d-285778b1d8ba",
            "title": "Me time",
            "duration": "1"
        },
        {
            "id": "b5fa56c5-3619-41e4-a78f-b468cea90681",
            "title": "Breakfast",
            "duration": "1",
            "after_time": 6,
            "before_time": 9
        },
        {
            "id": "7f69d43e-727d-40b7-be8a-47ab2e619c19",
            "title": "Walk",
            "duration": "1",
            "after_time": 14,
            "before_time": 20
        },
        {
            "id": "6ff579f6-c1f7-4239-8179-db706856042f",
            "title": "Dinner",
            "duration": "1",
            "after_time": 18,
            "before_time": 21
        },
        {
            "id": "2f8d406e-0df2-43ac-a7aa-6e65ff1c5c95",
            "title": "Water the plants indoors",
            "duration": "1",
            "start": "2023-01-03T00:00:00",
            "after_time": 1,
            "before_time": 3
        }
    ]
}
```
And the scheduler is outputting this:
```
{
    "scheduled": [
        {
            "taskid": 0,
            "goalid": "b669fc8f-a431-43e2-952d-285778b1d8ba",
            "title": "Me time",
            "duration": 1,
            "start": "2023-01-03T00:00:00",
            "deadline": "2023-01-03T01:00:00"
        },
        {
            "taskid": 1,
            "goalid": "2f8d406e-0df2-43ac-a7aa-6e65ff1c5c95",
            "title": "Water the plants indoors",
            "duration": 1,
            "start": "2023-01-03T01:00:00",
            "deadline": "2023-01-03T02:00:00"
        },
        {
            "taskid": 2,
            "goalid": "db01411c-6b57-4191-8c8b-733ac3751da3",
            "title": "hurdle",
            "duration": 1,
            "start": "2023-01-03T03:00:00",
            "deadline": "2023-01-03T04:00:00"
        },
        {
            "taskid": 3,
            "goalid": "b5fa56c5-3619-41e4-a78f-b468cea90681",
            "title": "Breakfast",
            "duration": 1,
            "start": "2023-01-03T06:00:00",
            "deadline": "2023-01-03T07:00:00"
        },
        {
            "taskid": 4,
            "goalid": "b898414d-76d5-4955-891d-b7c4ed7aac62",
            "title": "Lunch",
            "duration": 1,
            "start": "2023-01-03T12:00:00",
            "deadline": "2023-01-03T13:00:00"
        },
        {
            "taskid": 5,
            "goalid": "7f69d43e-727d-40b7-be8a-47ab2e619c19",
            "title": "Walk",
            "duration": 1,
            "start": "2023-01-03T14:00:00",
            "deadline": "2023-01-03T15:00:00"
        },
        {
            "taskid": 6,
            "goalid": "6ff579f6-c1f7-4239-8179-db706856042f",
            "title": "Dinner",
            "duration": 1,
            "start": "2023-01-03T18:00:00",
            "deadline": "2023-01-03T19:00:00"
        },
        {
            "taskid": 7,
            "goalid": "db01411c-6b57-4191-8c8b-733ac3751da3",
            "title": "hurdle",
            "duration": 1,
            "start": "2023-01-04T00:00:00",
            "deadline": "2023-01-04T01:00:00"
        },
        {
            "taskid": 8,
            "goalid": "e100fe8e-0c19-4a6f-b638-ef82107ea13b",
            "title": "Sleep",
            "duration": 8,
            "start": "2023-01-09T22:00:00",
            "deadline": "2023-01-10T06:00:00"
        }
    ],
    "impossible": []
}
```
For the "hurdle" goal, as @tijlleenders currently the scheduler will split goals if it's not possible to schedule them whole.  So that's not a bug.

**Bugs**

However there are two bugs I've noticed in the output: 
1) Task id 2 ("hurdle") is scheduled at 3am to 4am despite the "hurdle" goal having before_time of 3. 
2) For some reason, sleep is scheduled on the last possible day, not sure why that's happening.

Will look into both.

**Comment by egithinji** [comment] 2023-01-03 08:50
So I've pushed a fix for bug 1.

Bug 2 is actually not a bug! What's happening is on each day of the week, "Sleep" cannot be scheduled because it's time conflicts with "Water the plants indoors" and "Breakfast". 

The only day when it doesn't detect a conflict with them is the last day of the week. This is because "Water the plants indoors" and "Breakfast" do not have slots assigned on 10th Jan 2023.

**Closed** 2023-01-03 16:54 UTC
Labels: bug
