### ISSUE TITLE
test cases take much time to run

### ISSUE THREAD

**Issue by moaz-mokhtar** [tijlleenders/ZinZen-scheduler#356] opened 2023-07-03 12:53 UTC
**Describe the bug**
After PR https://github.com/tijlleenders/ZinZen-scheduler/pull/344, found that cases below running in too much time which is illogical.

Cases as below:
```shell
test e2e::children_with_over_duration has been running for over 60 seconds
test e2e::flex_duration_1 has been running for over 60 seconds
test e2e::i309 has been running for over 60 seconds
```
Maybe there are other cases, so need to confirm!

**Comment by tijlleenders** [comment] 2023-07-11 18:31
@moaz-mokhtar 
Do they also run this long without all the logging?

**Comment by moaz-mokhtar** [comment] 2023-07-11 18:41
Yes.
General test doesnt include debug logs and the same issue.

**Comment by tijlleenders** [comment] 2023-07-14 05:15
This is a great one to run the flamegraph on. Then we can see where the hot loops are.  
I suspect big min_duration goals being split into 1h Steps could be a reason. If it is confirmed by the flamegraph then this can be fixed by not splitting these into separate Steps. They all have the same flexibility anyway since they're identical. Only difference is that we should not forget it's not a block goal when remaining time drops to 8 or lower:
- the placer should take care to not schedule the min_duration, but just one hour - even if min_duration drops below 8
- the flex calculation should know this too - as at some point it could erroneously be seen as a block goal

**Comment by tijlleenders** [comment] 2023-09-09 13:23
Current tests don't take too long to run. Problem seems to be solved: `sys  0m1.673s`  
Will look at the perf to find any real problems (issue #210).

**Closed by tijlleenders** 2023-09-09 13:23 UTC
Labels: bug
